version: '3'

services:
  postgres:
    container_name: whaticket
    image: postgres
    environment:
      POSTGRES_USER: whaticket
      POSTGRES_PASSWORD: whaticket
      POSTGRES_DB: whaticket
    ports:
      - "5432:5432"
    volumes:
      - whaticket-data:/var/lib/postgresql/data

volumes:
  whaticket-data:
